server.port=${PORT:8080}

spring.application.name=api-gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# AUTH SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# USER SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=${USER_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**

# MEDICINE SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=medicine-service
spring.cloud.gateway.server.webflux.routes[2].uri=${MEDICINE_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/medicines/**

# ORDER SERVICE
spring.cloud.gateway.server.webflux.routes[4].id=order-service
spring.cloud.gateway.server.webflux.routes[4].uri=${ORDER_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/orders/**

# BILLING SERVICE
spring.cloud.gateway.server.webflux.routes[5].id=billing-service
spring.cloud.gateway.server.webflux.routes[5].uri=${BILLING_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/billing/**

# NOTIFICATION SERVICE
spring.cloud.gateway.server.webflux.routes[6].id=notification-service
spring.cloud.gateway.server.webflux.routes[6].uri=${NOTIFICATION_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/notifications/**


# DOCTOR SERVICE
spring.cloud.gateway.server.webflux.routes[8].id=doctor-service
spring.cloud.gateway.server.webflux.routes[8].uri=${DOCTOR_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/doctor/**

# HOSPITAL SERVICE
spring.cloud.gateway.server.webflux.routes[9].id=hospital-service
spring.cloud.gateway.server.webflux.routes[9].uri=${HOSPITAL_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/hospital/**

# EUREKA CONFIG
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443


# ===============================
# CORS CONFIG FOR FRONTEND
# ===============================

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=${FRONTEND_URL}
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].exposedHeaders=Set-Cookie,Authorization
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].maxAge=3600


# ===============================
# RENDER / PROXY / HTTPS HEADERS
# ===============================

spring.cloud.gateway.server.webflux.forwarded.enabled=true


# ===============================
# ACTUATOR
# ===============================

management.endpoint.health.show-details=always


# ===============================
# TIMEOUT CONFIG
# ===============================

spring.cloud.gateway.httpclient.connect-timeout=10000
spring.cloud.gateway.httpclient.response-timeout=60s


# ===============================
# LOGGING
# ===============================

logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty.http.client=INFO
logging.level.org.springframework.web=INFO

# FOR RENDER / PROXY
server.forward-headers-strategy=framework

# ACTUATOR
management.endpoints.web.exposure.include=health,info,gateway