server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# AUTH SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# USER SERVICE
spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**

# MEDICINE SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=medicine-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://medicine-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/medicines/**

# INVENTORY SERVICE
spring.cloud.gateway.server.webflux.routes[3].id=inventory-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/inventory/**

# ORDER SERVICE
spring.cloud.gateway.server.webflux.routes[4].id=order-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/orders/**

# BILLING SERVICE
spring.cloud.gateway.server.webflux.routes[5].id=billing-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://billing-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/billing/**

# NOTIFICATION SERVICE
spring.cloud.gateway.server.webflux.routes[6].id=notification-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/notifications/**

# NOTIFICATION WEBSOCKET
spring.cloud.gateway.server.webflux.routes[7].id=notification-websocket
spring.cloud.gateway.server.webflux.routes[7].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/notifications-ws/**

# EUREKA CONFIG
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ACTUATOR
management.endpoints.web.exposure.include=health,info,gateway