# Server
server.port=8090

# Application Name
spring.application.name=hospital-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/medirevolution_hospital
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# JWT Configuration
jwt.secret=7f4b5f12e1d64df1a8a7d19e6d3b91a87f4b5f12e1d64df1a8a7d19e6d3b91a8
phonepe.base-url=${PHONEPE_BASE_URL:https://api-preprod.phonepe.com/apis/pg-sandbox}
phonepe.client-id=${PHONEPE_CLIENT_ID:M22ZRFX2Q40BX_2606151756}
phonepe.client-secret=${PHONEPE_CLIENT_SECRET:NmZlOWRhOWMtMTBmYy00NTAwLWE4MDgtMDgzZmIyYzkzYzhi}
phonepe.client-version=${PHONEPE_CLIENT_VERSION:1}

app.payment.redirect-url=${PAYMENT_REDIRECT_URL:http://localhost:8087/payment-success}
# Logging
logging.level.org.springframework.security=INFO