package com.example.medi.saas.enums;

public enum TenantModule {
    DASHBOARD,
    PATIENTS,
    APPOINTMENTS,
    DOCTORS,
    STAFF,
    PRESCRIPTIONS,
    DOCTOR_AVAILABILITY,
    OPD,
    IPD,
    BILLING,
    PHARMACY,
    INVENTORY,
    LAB,
    RADIOLOGY,
    REPORTS,
    NOTIFICATIONS,
    SETTINGS,
    PERMISSIONS,
    
 // Wholesaler/Retailer modules
 	MEDICINE_MASTER,
 	SUPPLIERS,
 	CUSTOMERS,
 	PURCHASES,
 	SALES,
 	SALES_ORDERS,
 	PURCHASE_RETURNS,
 	SALES_RETURNS,
 	PAYMENTS,
 	EXPIRY_MANAGEMENT
}