server.port=${PORT:8080}

spring.application.name=user-service

# DATABASE CONFIG
spring.datasource.url=${USER_DB_URL:jdbc:postgresql://localhost:5432/medirevolution_user}
spring.datasource.username=${USER_DB_USERNAME:postgres}
spring.datasource.password=${USER_DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=user_service
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File Upload Directory
file.upload-dir=${UPLOAD_DIR:uploads/user-service}

# Multipart File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# EUREKA CONFIG
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443

server.forward-headers-strategy=framework

# JWT CONFIG
jwt.secret=${JWT_SECRET:7f4b5f12e1d64df1a8a7d19e6d3b91a87f4b5f12e1d64df1a8a7d19e6d3b91a8}