# Server
server.port=8089

# Application Name
spring.application.name=doctor-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/medirevolution_doctor
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Eureka Registration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Logging
logging.level.org.springframework.security=INFO

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT Configuration
jwt.secret=7f4b5f12e1d64df1a8a7d19e6d3b91a87f4b5f12e1d64df1a8a7d19e6d3b91a8



# ===============================
# PhonePe PG Sandbox
# ===============================
phonepe.base-url=https://api-preprod.phonepe.com/apis/pg-sandbox
phonepe.client-id=actual_client_id_from_phonepe
phonepe.client-secret=actual_client_secret_from_phonepe
phonepe.client-version=actual_client_version_from_phonepe

app.payment.redirect-url=http://localhost:8080/payment-success