# Server
server.port=${PORT:8080}

# Application Name
spring.application.name=doctor-service

# Database Configuration
spring.datasource.url=${DOC_DB_URL:jdbc:postgresql://localhost:5432/medirevolution_doctor}
spring.datasource.username=${DOC_DB_USERNAME:postgres}
spring.datasource.password=${DOC_DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=doctor_service
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Registration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443

server.forward-headers-strategy=framework

# Logging
logging.level.org.springframework.security=INFO

# JWT Configuration
jwt.secret=${JWT_SECRET:7f4b5f12e1d64df1a8a7d19e6d3b91a87f4b5f12e1d64df1a8a7d19e6d3b91a8}

# ===============================
# PhonePe PG Sandbox
# ===============================
phonepe.base-url=${PHONEPE_BASE_URL:https://api-preprod.phonepe.com/apis/pg-sandbox}
phonepe.client-id=${PHONEPE_CLIENT_ID:M22ZRFX2Q40BX_2606151756}
phonepe.client-secret=${PHONEPE_CLIENT_SECRET:NmZlOWRhOWMtMTBmYy00NTAwLWE4MDgtMDgzZmIyYzkzYzhi}
phonepe.client-version=${PHONEPE_CLIENT_VERSION:1}

app.payment.redirect-url=${PAYMENT_REDIRECT_URL:http://localhost:8080/payment-success}