server.port=${PORT:8080}

spring.application.name=order-service

# DATABASE CONFIG
spring.datasource.url=${ORD_DB_URL:jdbc:postgresql://localhost:5432/medirevolution_order}
spring.datasource.username=${ORD_DB_USERNAME:postgres}
spring.datasource.password=${ORD_DB_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=order_service
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# HIKARI CONNECTION POOL - VERY IMPORTANT FOR MULTIPLE MICROSERVICES
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# EUREKA CONFIG
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443

server.forward-headers-strategy=framework

# JWT CONFIG
jwt.secret=${JWT_SECRET:7f4b5f12e1d64df1a8a7d19e6d3b91a87f4b5f12e1d64df1a8a7d19e6d3b91a8}