server.port=${PORT:8761}

spring.application.name=discovery-service

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Render public hostname
eureka.instance.hostname=medirevolution-user-service.onrender.com
eureka.instance.prefer-ip-address=false

# Render uses HTTPS outside
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443

# Proxy headers
server.forward-headers-strategy=framework

# Optional actuator
management.endpoints.web.exposure.include=health,info