package com.example.medi.saas.service;

import com.example.medi.saas.entity.SaasTenantSetting;
import com.lowagie.text.*;
import org.springframework.stereotype.Service;

@Service
public class SaasPdfBrandingService {

    private final SaasTenantSettingService settingService;

    public SaasPdfBrandingService(SaasTenantSettingService settingService) {
        this.settingService = settingService;
    }

    public SaasTenantSetting getBranding(Long tenantId) {
        return settingService.getSettingEntityOrDefault(tenantId);
    }

    public void addHeader(Document document, Long tenantId, String documentTitle) {

        SaasTenantSetting branding = getBranding(tenantId);

        try {
            Font businessFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 10);
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);

            Paragraph businessName = new Paragraph(safe(branding.getBusinessName()), businessFont);
            businessName.setAlignment(Element.ALIGN_CENTER);
            document.add(businessName);

            Paragraph address = new Paragraph(buildAddress(branding), normalFont);
            address.setAlignment(Element.ALIGN_CENTER);
            document.add(address);

            Paragraph contact = new Paragraph(buildContact(branding), normalFont);
            contact.setAlignment(Element.ALIGN_CENTER);
            document.add(contact);

            if (branding.getGstNumber() != null && !branding.getGstNumber().isBlank()) {
                Paragraph gst = new Paragraph("GST: " + branding.getGstNumber(), normalFont);
                gst.setAlignment(Element.ALIGN_CENTER);
                document.add(gst);
            }

            document.add(Chunk.NEWLINE);

            Paragraph title = new Paragraph(documentTitle, titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            document.add(Chunk.NEWLINE);

        } catch (Exception e) {
            throw new RuntimeException("Unable to add PDF branding header");
        }
    }

    public void addFooter(Document document, Long tenantId, String footerText) {

        SaasTenantSetting branding = getBranding(tenantId);

        try {
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 9);

            document.add(Chunk.NEWLINE);

            String finalFooter = footerText;

            if (finalFooter == null || finalFooter.isBlank()) {
                finalFooter = "Generated by MediRevolution SaaS";
            }

            Paragraph footer = new Paragraph(finalFooter, normalFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            if (branding.getWebsite() != null && !branding.getWebsite().isBlank()) {
                Paragraph website = new Paragraph(branding.getWebsite(), normalFont);
                website.setAlignment(Element.ALIGN_CENTER);
                document.add(website);
            }

        } catch (Exception e) {
            throw new RuntimeException("Unable to add PDF branding footer");
        }
    }

    private String buildAddress(SaasTenantSetting branding) {
        StringBuilder sb = new StringBuilder();

        append(sb, branding.getAddress());
        append(sb, branding.getCity());
        append(sb, branding.getState());
        append(sb, branding.getPincode());
        append(sb, branding.getCountry());

        return sb.length() == 0 ? "-" : sb.toString();
    }

    private String buildContact(SaasTenantSetting branding) {
        StringBuilder sb = new StringBuilder();

        if (branding.getContactMobile() != null && !branding.getContactMobile().isBlank()) {
            sb.append("Mobile: ").append(branding.getContactMobile());
        }

        if (branding.getContactEmail() != null && !branding.getContactEmail().isBlank()) {
            if (sb.length() > 0) {
                sb.append(" | ");
            }
            sb.append("Email: ").append(branding.getContactEmail());
        }

        return sb.length() == 0 ? "-" : sb.toString();
    }

    private void append(StringBuilder sb, String value) {
        if (value == null || value.isBlank()) {
            return;
        }

        if (sb.length() > 0) {
            sb.append(", ");
        }

        sb.append(value);
    }

    private String safe(String value) {
        return value == null || value.isBlank() ? "MediRevolution SaaS" : value;
    }
}