server.port=${PORT:8081}

spring.application.name=auth-service

# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/medirevolution_auth
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=auth_service
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.mail.from=shansharma9050@gmail.com
# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shansharma9050@gmail.com
spring.mail.password=kodn sdma mvwb ogff

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# EUREKA CONFIG
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT CONFIG
jwt.secret=7f4b5f12e1d64df1a8a7d19e6d3b91a87f4b5f12e1d64df1a8a7d19e6d3b91a8
jwt.expiration=86400000