server.port=8095

spring.application.name=saas-service

# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/medirevolution_saas
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# HIKARI CONNECTION POOL - VERY IMPORTANT FOR MULTIPLE MICROSERVICES
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# EUREKA CONFIG
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT CONFIG
jwt.secret=7f4b5f12e1d64df1a8a7d19e6d3b91a87f4b5f12e1d64df1a8a7d19e6d3b91a8